### ISSUE TITLE
TypeError: Object  has no method 'join'

### ISSUE THREAD

**Issue by hsume2** [jfromaniello/npm-install-retry#6]
Hi @jfromaniello,

I noticed the following error most likely introduced by https://github.com/jfromaniello/npm-install-retry/pull/5.

```
/harmony/code/zendesk_console/node_modules/npm-install-retry/index.js:7
    var runCmd = command + ' ' + args.join(' ');
                                      ^
TypeError: Object  has no method 'join'
    at run (/harmony/code/zendesk_console/node_modules/npm-install-retry/index.js:7:39)
    at module.exports (/harmony/code/zendesk_console/node_modules/npm-install-retry/index.js:26:3)
    at Object.<anonymous> (/harmony/code/zendesk_console/node_modules/npm-install-retry/bin/npm-install-retry:15:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

Let me know if you need any additional information, thanks!

**Comment by jfromaniello** [comment]
thanks for reporting this

**Comment by hsume2** [comment]
Thanks for the quick fix! :+1:
